# -*- coding: utf-8 -*-
"""Assignment-008/8 (Leap Years).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12llS5hMpvlllj7u8yYnz-_kBEMxUIikE
"""

leap = int(input("enter a leap year: "))
condition = (leap%400 == 0) or (leap % 4 == 0 and leap%100 != 0 )
if condition:
  print(leap, "is leap year")
else:
  print(leap, "is not leap year")